{"version":3,"sources":["../../Promise/test3.js"],"names":["rejectedTh","then","resolve","cc","rej","Promise","catch","console","log","d"],"mappings":";;AAAA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA,IAAIA,aAAa;AACfC,QAAM,cAASC,OAAT,EAAkBC,EAAlB,EAAsB;AAC1BA,OAAG,KAAH;AACD;AAHc,CAAjB;;AAMA,IAAIC,MAAMC,QAAQH,OAAR,CAAgBF,UAAhB,EAA4BM,KAA5B,CAAkC;AAAA,SAAKC,QAAQC,GAAR,CAAYC,CAAZ,CAAL;AAAA,CAAlC,CAAV","file":"test3.js","sourcesContent":["// const p = {\n//   then: function(cb, errcb) {\n//     cb(42);\n//     errcb('111');\n//   },\n// };\n//\n// p.then(function(v1) {\n//   console.log(v1);\n// }, function(v2) {\n//   console.log(v2);\n// });\n//\nlet rejectedTh = {\n  then: function(resolve, cc) {\n    cc('123');\n  },\n};\n\nlet rej = Promise.resolve(rejectedTh).catch(d => console.log(d));"]}